<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2015-05-14 11:22:52
 */
return [
    'application' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@cdn/assets',
        'js' => [
            'application-64ff58ee04efc9c9e26c6e27e7dd4b04.js',
        ],
        'css' => [
            'application-15bf3d8a2a80812c5c1046f5046fab3a.css',
        ],
    ],
    'landingpage' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@cdn/assets',
        'js' => [
            'index-62b28589249fb87f182301c07af907a1.js',
        ],
        'css' => [
            'index-0d17de52fd714612a5dc6dceefa8ec04.css',
        ],
    ],
    'about' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@cdn/assets',
        'js' => [
            'about-96413f3c531757c61501635495048242.js',
        ],
        'css' => [
            'about-5007943f2120761882598f7a4aea7fcd.css',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'application',
        ],
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'application',
        ],
    ],
    'app\\assets\\AdminLTEAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\bootstrap\\BootstrapAsset',
            'yii\\web\\JqueryAsset',
            'application',
        ],
    ],
    'app\\assets\\AngularAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'application',
        ],
    ],
    'app\\assets\\AngularAppAsset' => [
        'depends' => [
            'app\\assets\\AdminLTEAsset',
            'app\\assets\\AngularAsset',
            'yii\\bootstrap\\BootstrapAsset',
        ],
        'sourcePath' => null,
        'basePath' => null,
        'baseUrl' => null,
        'js' => [],
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'app\\assets\\AngularAppAsset',
    ],
    'app\\assets\\IndexPageAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AngularAppAsset',
            'landingpage',
        ],
    ],
    'app\\assets\\AngularBootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'about',
        ],
    ],
    'app\\assets\\AboutPageAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AngularAppAsset',
            'app\\assets\\AngularBootstrapAsset',
            'about',
        ],
    ],
];